# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    
- script: pip install -e ".[dev]"
  displayName: 'Pip install'
  
- script: |
    python -m pip install flake8
    flake8 .
  displayName: 'Run lint tests'

- script: |
    CUR_PATH=$(pwd)
    export AIRFLOW_HOME=${CUR_PATH}/test/airflow_home
    export PYTHONPATH=${CUR_PATH}/src:${CUR_PATH}/test
    cd test/
    pytest conftest.py
    pytest . -s --doctest-modules --junitxml=junit/test-results.xml --cov=airtunnel --cov-report=xml --cov-report=html
  displayName: 'Test with pytest'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

- script: |
    CUR_PATH=$(pwd)
    python -m pip install coverage-badge

    cd test/ && coverage-badge -o coverage.svg

    mkdir -p ${CUR_PATH}/assets
    mv ${CUR_PATH}/test/coverage.svg ${CUR_PATH}/assets/coverage.svg

    git config --global user.email "joerg@joerg-schneider.org"
    git config --global user.name "joerg-schneider"

    git add ${CUR_PATH}/assets/coverage.svg
    git checkout gh-pages

    git commit -m "AzureDevOps: updated coverage.svg for master"
    git push
  displayName: 'Coverage badge'

