# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- feature/*
- bugfix/*
- release/*

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

variables:
- group: airtunnel

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: |
    python -m pip install tox
    tox --version
  displayName: 'Install Tox'

- script: |
    tox -e lint
  displayName: 'Tox Lint'

- script: |
    tox -e docs
  displayName: 'Tox Sphinx Docs'

- script: |
    CUR_PATH=$(pwd)

    mv ${CUR_PATH}/docs/_build/html /tmp/html

    git config --global user.email "joerg@joerg-schneider.org"
    git config --global user.name "joerg-schneider"

    git checkout gh-pages
    git ls-files | xargs git rm

    mv /tmp/html/* ${CUR_PATH}/
    touch .nojekyll

    git add *.html
    git add .nojekyll
    git add *.js
    git add _images
    git add _sources
    git add _static
    git add api
    git commit -m "AzureDevOps: updated docs"
    #git push https://$(AIRTUNNEL_PAT)@github.com/joerg-schneider/airtunnel-dev.git
  displayName: 'Publish Docs'