# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- feature/*
- bugfix/*
- release/*

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

variables:
- group: airtunnel

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: |
    python -m pip install tox
    tox --version
  displayName: 'Install Tox'

- script: |
    tox -e lint
  displayName: 'Tox Lint'

- script: |
    CUR_PATH=$(pwd)
    export AIRFLOW_HOME=${CUR_PATH}/test/airflow_home
    tox -e py37
  displayName: 'Run Tox Python 3.7'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: |
    CUR_PATH=$(pwd)
    export AIRFLOW_HOME=${CUR_PATH}/test/airflow_home
    tox -e py36
  displayName: 'Run Tox Python 3.6'


- script: |
    tox -e coverage
  displayName: 'Tox Combine Coverage'